# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9b871ba11c47bd73d6bfeb96927d4d53"
name = "SDS Manager App"
handle = "new-sds"
application_url = "https://digital-newly-goes-chapel.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "rohit-cybersify.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://digital-newly-goes-chapel.trycloudflare.com/auth/callback",
  "https://digital-newly-goes-chapel.trycloudflare.com/auth/shopify/callback",
  "https://digital-newly-goes-chapel.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
